let filters = [
  { title : "연령",
    fieldName : "age",
    items : ["유소년", "어린이", "학생", "성인"],
  },
  { title : "실내/실외",
    fieldName : "inout",
    items : ["실내마장", "실외마장", "외승"],
  },
  { title : "프로그램",
    fieldName : "program",
    items : ["체험승마", "취미승마"],
  },
  { title : "난이도",
    fieldName : "difficulty",
    items : ["초급승마", "중급승마", "상급승마"],
  },
  { title : "레슨",
    fieldName : "lesson",
    items : ["레슨체험", "레슨", "원형레슨", "속성레슨", "고급레슨", "중급레슨", "초급레슨"],
  },
  { title : "환경",
    fieldName : "environment",
    items : ["초원승마", "해변승마", "산악승마", "트랙승마"],
  },
  { title : "말",
    fieldName : "horse",
    items : ["웜블러드", "더러블렛", "포니", "한라마", "조랑말"],
  },
  { title : "빠르기별",
    fieldName : "speed",
    items : ["산책", "달리기"],
  },
  { title : "특수프로그램",
    fieldName : "special",
    items : ["재활승마", "트래킹 코스"],
  },
]
exports.filters = filters
